### ISSUE TITLE
Workspace not reopened when switching browsers

### ISSUE THREAD

**Issue by ntimo** [coder/code-server#2161]
# Description:
When opening a workspace file in code server and then switching to another browser or device code server will not reopen the exact same workspace.

# Reproduce
1. Open workspace file
2. Open code server in a different browser

- Web Browser: Chrome, Safari
- Local OS: macOS 10.15.7 (19H2)
- Remote OS: Ubuntu Server 20.04
- Remote Architecture: amd64
- `code-server --version`: 3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a

Relates to: https://github.com/cdr/code-server/discussions/2154

**Comment by ntimo** [comment]
I am not sure if this is related to the bug, but opened terminal windows will also be lost :(

**Comment by code-asher** [comment]
Does this still happen in the latest release? I'm not able to reproduce.

Check out https://github.com/cdr/code-server/issues/2276 for persisting terminals.

**Comment by nhooyr** [comment]
I was able to reproduce on the latest version.

<img width="547" alt="Screen Shot 2021-01-20 at 1 57 52 PM" src="https://user-images.githubusercontent.com/10180857/105221714-7fbee080-5b27-11eb-8308-079cf1fcf993.png">

Not sure if this is a bug or intended bug. Should code-server prompt me to open the workspace or automatically open it?

**Comment by nhooyr** [comment]
Wait actually it worked this time for me? Hold on...

**Comment by nhooyr** [comment]
Yea nvm I was confused, I tested and it works well.

@ntimo let us know if you can still reproduce on the latest release and I'll reopen.

**Comment by ankit-gautam-pyxis** [comment]
I can easily reproduce it. When i open it in same browser then it works. Different Profiles in mac or different browsers or different devices it remembers nothing. 

OS: Mac Monterey

https://user-images.githubusercontent.com/77270664/139521417-7cfeae99-6e8c-4396-9c7b-3d89d87badaa.mp4

**Comment by bugwheels94** [comment]
Hi, This bug is very problematic and defeats the main purpose of anyone using code-server in first place. Any update on this?

**Comment by jsjoeio** [comment]
@code-asher we fixed this in the upcoming release, right?

**Comment by code-asher** [comment]
I think this should work in the next release.

**Comment by jsjoeio** [comment]
Great, we'll test when 4.0.1 comes out.

**Comment by jsjoeio** [comment]
@bugwheels94 that would be very helpful!

**Comment by bosmart** [comment]
I still have this problem in the latest version 4.11.0. I have a workspace open with terminal windows etc., when I try to access in another browser and the windows/terminals are no longer there.

**Comment by spkane** [comment]
We are discussing this in some detail here:

https://github.com/coder/code-server/issues/3061#issuecomment-1749307072

**Comment by code-asher** [comment]
I believe we got this fixed!
