### ISSUE TITLE
Dynamically webview resources fail to load in some browser/OS combinations

### ISSUE THREAD

**Issue by chouzz** [coder/code-server#3410]
Hi, I have two issues, they may all be related to https certificates.

- One is `code-server` prompt can‘t register serviceworker error
- The other is that I can't `load resources dynamically` on my expansion webview.

I run `code-server --host 0.0.0.0 --port 8223 --cert`  in docker `ubuntu:20.04`, and expose `8223` in my Windows 10 host, but I get an ssl error when I open a exntesion webview in code-server in my company.

when I use `Chrome  command line` "**--ignore-certificate-errors**", my extension webview can't dynamic loading of resources(eg. js, css), which cause the page style confusion, the Chrome dev tool network display the resource keep pending until it fails.

At first, I thought it was the invalid certificate problem，but even if I use a valid certificate, I **still** can't dynamic loading resources.(**Without any certificate errors and any Chrome command line options**)

I use something like this to dynamic loading resources
```
  function addCss(path, callback) {
      if(!checkcache(path)) { /*Check if it has been loaded*/
          var head = dom.getElementsByTagName('head')[0];
          var link = dom.createElement('link');
          link.href = path;
          link.rel = 'stylesheet';
          link.type = 'text/css';
          head.appendChild(link); /*Add to HTML*/
          link.onload = link.onreadystatechange = function() { /*whether the loading is successful*/
              if(!this.readyState || this.readyState === "loaded" || this.readyState === "complete") {
                  link.onload = link.onreadystatechange = null;
                  callback();
              }
          };
          cache[path] = 1; /*Store loaded paths*/
      }
  };
```

-->

## OS/Web Information

- Web Browser: Chrome 90.0.4430.212 64bit
- Local OS: Windows 10
- Remote OS: ubuntu:20.04 (docker)
- Remote Architecture: x86
- `code-server --version`: 3.9.0

## Steps to Reproduce

1. installl code-server 3.9.0 in docker ubuntu:20.04
2. code-server --host 0.0.0.0 --port 8223 --cert
3. enter localhost:8888 and open my extension webview

## Expected

No error.

## Actual

get an error in bottom right corner:
```
Error loading webview: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://localhost:8223/webview/') with script ('https://localhost:8223/webview/service-worker.js'): An SSL certificate error occurred when fetching the script.
```

## Screenshot

![image](https://user-images.githubusercontent.com/18023066/118653196-db6d5200-b819-11eb-94bd-0091f9fbd2b3.png)

**Comment by code-asher** [comment]
So this happens even with a valid certificate when you don't get any certificate errors right?

Could you post the browser log when you try this with a valid certificate? I wonder if the resources are getting blocked by CSP or something.

**Comment by chouzz** [comment]
Yes. 
- With a valid certificate, `no any errors`, I **can't load resources dynamically** on my expansion webview.
- With a self-signed certificate(use --cert),  I got an error `"loading webivew error"`(above screentshot), but loading resources dynamically **works fine**.
- With http, I got a `"Your Connection is Not Private"` warning from Chrome, loading resources dynamically **works fine too**.

Here are the logs, I didn't see any other warning or errors related to certificate except these, seems there are no useful information about these errors, they just show **net::ERR_FAILED** after pending for several minutes .

![image](https://user-images.githubusercontent.com/18023066/118745248-5cfbc900-b888-11eb-855c-dfc070cd2bd7.png)

![image](https://user-images.githubusercontent.com/18023066/118745420-b8c65200-b888-11eb-935e-07bde206df8a.png)

**Comment by chouzz** [comment]
With the latest c**ode-server** and **valid certificate**，I still can't load resources dynamically on webview. The example extension repo is [here](https://github.com/chouzz/code-server-webview), you can download extension from [here](https://github.com/chouzz/code-server-webview/releases/tag/v0.0.1), this extension is just a little modified from [vscode-webview-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample).

## Steps to Reproduce:
1. install code-server-webview-0.0.1.vsix with latest code-server
2. Run command "Start cat coding session", and open Chrome Developer Tools, 
3. Click button "click me"

## Expected
get "hello wrold test.js" from console, which means test.js is loaded successfully.

## Actual
test.js is keep pending , and get a net::ERR_FAILED error finally.

## Screenshot
![image](https://user-images.githubusercontent.com/18023066/118991030-f70d5f80-b9b5-11eb-93a7-347d2af0c4b1.png)

## Possible problems
The requested resource test.js without cookies(Not sure). 

Please let me know if you have any ideas!

**Comment by chouzz** [comment]
I am sure it is related to **service-worker** in `lib\vscode\src\vs\workbench\contrib\webview\browser\pre\service-worker.js`.

when I use localhost with self-signed certificate, I got an error "could not register service workers", service workers will not be used in this scene. So that loading resources dynamically works fine.

With an valid certificate, service workers can be registered，when loading resources dynamically, eventListener "fetch" in service-worker.js will be triggered, there maybe something wrong here.

**Comment by code-asher** [comment]
Ahhhhhh I haven't had a chance to try the example yet but that makes a lot of sense. 

If I recall correctly VS Code intercepts requests from the web view (which is an iframe) using the service worker and routes them through the parent frame instead.

I think you're right that something must be wrong there.

**Comment by code-asher** [comment]
Interesting, I don't get this on Linux + Firefox/Chromium but I do get this on Windows + Chrome.

**Comment by chouzz** [comment]
That's strange，so this problem may be related to the browser? Do you know there are other ways to avoid this problem？

**Comment by code-asher** [comment]
I haven't debugged yet to see where exactly the issue lies but I think there must be some combination of the service worker and browser that is causing a problem.

At the moment I can't think of any workarounds other than somehow avoiding dynamically loaded resources. :disappointed: We'll need to do more testing.

**Comment by mmitkevich** [comment]
I had similar problem with latest release 3.10, had to downgrade to 3.8. 
OSX/Chrome 91.0.4472.114

**Comment by Kaka1127** [comment]
I also met the same issue with the latest version 3.11.1. We need to downgrade to 3.8.1 to work correctly
I hope to fix this issue...

**Comment by jsjoeio** [comment]
@Kaka1127 this should be fixed in the next release!

**Comment by Kaka1127** [comment]
@jsjoeio 

It was good to know!

**Comment by chouzz** [comment]
> @Kaka1127 this should be fixed in the next release!

Just curious, why does this happen? Why is there such an error？@jsjoeio

**Comment by jsjoeio** [comment]
Well...originally, I was thinking this was related to the service worker path (which we messed up when we refactored something things) 🤔

> With an valid certificate, service workers can be registered，when loading resources dynamically, eventListener "fetch" in service-worker.js

But...now I'm seeing this comment, which could mean that the issue is related to this: https://github.com/cdr/code-server/issues/2760

I guess we'll have to test in the next release and see if it's still an issue but I'm hoping it's fixed 🤞

**Comment by Kaka1127** [comment]
@jsjoeio 
Yesterday, code-server was released new of v1.12.0. But it seems that it is not fixed this issue. Will you fix this issue on v1.12.1?

**Comment by jsjoeio** [comment]
> Yesterday, code-server was released new of v1.12.0. But it seems that it is not fixed this issue. Will you fix this issue on v1.12.1?

Ah, I think you mean 3.12.0. Thanks for testing! We have to prioritize some other things (improving the build and release process) but I will add it to the release after that! (Adding to On Deck for now)

**Comment by jsjoeio** [comment]
If someone else has time to poke around and see what a fix might be though, then that would help us address this faster! I just don't have the bandwidth for this next version milestone

**Comment by code-asher** [comment]
I updated the issue title, just FYI for anyone following this if you are having the `SecurityError` problem that means your browser is rejecting your TLS certificates and is not something code-server can fix.

**Comment by Blakeinstein** [comment]
I think I faced this way back in #3844

**Comment by DevXiaolan** [comment]
same issue , will it fixed in next version ?

**Comment by jsjoeio** [comment]
> I updated the issue title, just FYI for anyone following this if you are having the SecurityError problem that means your browser is rejecting your TLS certificates and it is likely not something code-server can fix.

@DevXiaolan I see you downvoted that comment. Are you seeing a different error?

**Comment by Blakeinstein** [comment]
> 
> 
> I updated the issue title, just FYI for anyone following this if you are having the `SecurityError` problem that means your browser is rejecting your TLS certificates and it is likely not something code-server can fix.

I dont think I could get it working over http either.

**Comment by code-asher** [comment]
Browser only allow service workers over HTTPS so HTTP will not work
unfortunately :(

**Comment by code-asher** [comment]
Unless you are using a secure context over HTTP like localhost?  But in that case it would show `SecurityError` so the problem would be something else and my comment can be ignored.

**Comment by Blakeinstein** [comment]
> Browsers only allow service workers over HTTPS so HTTP will not work
unfortunately :( 
That makes so much sense! Even monaco works over service workers, that means no monaco w/o https?

Perhaps a proxy for the webview worker to reuse the certificate? I was thinking it was looking at the wrong place as well.

**Comment by fritterhoff** [comment]
I've got a quite similar bug. Accessing the code server (behind a https reverseproxy) from MS Edge and Chrome works without any noticeable problems, opening the same setup in a current Mozilla Firefox causes CSP errors. If you need further information about the setup please let me know ;)

**Comment by jsjoeio** [comment]
> opening the same setup in a current Mozilla Firefox causes CSP errors. If you need further information about the setup please let me know ;)

Interesting.... cc @code-asher 

Do you mind providing the browser logs from Firefox? I wonder if they have stricter CSPs or something 🤔

**Comment by fritterhoff** [comment]
![grafik](https://user-images.githubusercontent.com/32478819/136085577-21040fa6-0dfd-486d-9dcb-c47c56c360ef.png)

**Comment by fritterhoff** [comment]
In comparison using MS Edge: 
![grafik](https://user-images.githubusercontent.com/32478819/136085935-8e77875f-72ca-4552-a47a-1eb42fd478f5.png)

**Comment by jsjoeio** [comment]
It's weird that it's failing to initialize VS Code. Is this the latest version of code-server? And what happens if you use an incognito window?

I'm also unsure about the "web worker extension host is started without an iframe sandbox!"

**Comment by fritterhoff** [comment]
Hi @jsjoeio,

I'm using the latest docker image (`codercom/code-server:latest`). That is running a code-server 3.12.0
![grafik](https://user-images.githubusercontent.com/32478819/136141464-df124743-14c4-4538-b979-e15489343a5e.png)

Running in an incognitor window: 
![grafik](https://user-images.githubusercontent.com/32478819/136141684-3a73a2f8-6dee-4fb8-857d-2b79bbe0501c.png)

**Comment by code-asher** [comment]
Oh I just saw that you wrote it was an incognito (private) window so that explains the lack of service workers.

I am not sure about the CSP issue.  This is on code-server 3.12.0?  I know we had a CSP issue in < 3.12.0.

**Comment by fritterhoff** [comment]
@code-asher Yep, the service worker is missing in the private window. I'm using code-server 3.12.0

**Comment by fritterhoff** [comment]
![grafik](https://user-images.githubusercontent.com/32478819/136238045-23735a64-de7a-405c-a971-865256d0c5ed.png)

**Comment by code-asher** [comment]
Thank you for the info! I was able to replicate on Firefox and code-server 3.12.0.

**Comment by fritterhoff** [comment]
Hello again,

Is there an update or a solution in sight? Sadly I don't have any experience in the development of vs code ;) Have you (maybe) thought about enabling the csp reporting functionality and debugging the issue that way?

**Comment by code-asher** [comment]
We should test this again once the next major release comes out (soon).

**Comment by fritterhoff** [comment]
Sadly the new version does not seem to improve the behavior.

**Comment by code-asher** [comment]
I was seeing CSP issues caused by the port mismatch in the other issue
so hopefully it is the same problem.

**Comment by code-asher** [comment]
Ah nope I still get this issue with the fix for the port.

**Comment by fritterhoff** [comment]
Mhm... Can I help you somehow?

**Comment by dantegarden** [comment]
verison 4.0.1 still meet the same issue, by the way my browser is Chrome96.0.4664.110.

**Comment by jsjoeio** [comment]
@dantegarden thanks for testing! Can you post basic repro steps?

**Comment by hhc87** [comment]
version 4.2.0\4.3.0\4.4.0 still meet the same issue, by the way my browser is Microsoft Edge 101.0.1210.47 and Chrome 101.0.4951.64.But it’s ok in Firefox 100.0.1 and both browser didn’t change any security config.

Environment:
centos 7
Docker with 2c1g container resource
Self SSL certificate

———————————————————————
The error in chrome and edge are as flow:

Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-webview.net&remoteAuthority=172.20.23.102'): An SSL certificate error occurred when fetching the script..

**Comment by jsjoeio** [comment]
@hhc87 any chance you can post repro steps? Last time I looked into this I couldn't reproduce

**Comment by hhc87** [comment]
> @hhc87 any chance you can post repro steps? Last time I looked into this I couldn't reproduce

I use docker to deploy the 4.4.0 version of code-server (offline environment) on centos7, and then install the plugin 'form generator plugin' developed by jakHuang through offline installation (can be obtained in the vscode app store), and the plugin's The remote connection address is configured as the same-origin address exposed by the code-server (eg: https://172.20.23.102/code-server and https://172.20.23.102/formgenerator ), meanwhile, the https certificate is issued locally by the linux server Generated certificate. The problem is that when I right-click the .vue file in the workspace and click 'Enter Form Designer', the code-server will report an error, and the error message is as follows:
-------------
Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-webview.net&remoteAuthority=172.20.23.102'): An SSL certificate error occurred when fetching the script..
----------
From the superficial exception information, it seems that the service worker does not recognize the self-created ssl certificate, and I don't know if it is allowed to use the service worker in the code-server which using the self-signed certificate.

hope to get your reply

**Comment by hhc87** [comment]
> @hhc87 any chance you can post repro steps? Last time I looked into this I couldn't reproduce

I use docker to deploy the 4.4.0 version of code-server (offline environment) on centos7, and then install the plugin 'form generator plugin' developed by jakHuang through offline installation (can be obtained in the vscode app store), and the plugin's The remote connection address is configured as the same-origin address exposed by the code-server (eg: https://172.20.23.102/code-server and https://172.20.23.102/formgenerator ), meanwhile, the https certificate is issued locally by the linux server Generated certificate. The problem is that when I right-click the .vue file in the workspace and click 'Enter Form Designer', the code-server will report an error, and the error message is as follows:

----------------

Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-webview.net&remoteAuthority=172.20.23.102'): An SSL certificate error occurred when fetching the script..

----------------
From the superficial exception information, it seems that the service worker does not recognize the self-created ssl certificate, and I don't know if it is allowed to use the service worker in the code-server which using the self-signed certificate.

Hope to get your reply

**Comment by hhc87** [comment]
> @hhc87 any chance you can post repro steps? Last time I looked into this I couldn't reproduce

@jsjoeio very happy to get your reply

I use docker to deploy the 4.4.0 version of code-server (offline environment) on centos7, and then install the plugin 'form generator plugin' developed by jakHuang through offline installation (can be obtained in the vscode app store), and the plugin's The remote connection address is configured as the same-origin address exposed by the code-server (eg: [https://172.20.23.102/code-server and https://172.20.23.102/formgenerator ](https://172.20.23.102/code-server%C2%A0and%C2%A0https://172.20.23.102/formgenerator%C2%A0)), meanwhile, the https certificate is issued locally by the linux server Generated certificate. The problem is that when I right-click the .vue file in the workspace and click 'Enter Form Designer', the code-server will report an error, and the error message is as follows:

------------------

Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://172.20.23.102/static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-webview.net&remoteAuthority=172.20.23.102'): An SSL certificate error occurred when fetching the script..

--------------------

From the superficial exception information, it seems that the service worker does not recognize the self-created ssl certificate, and I don't know if it is allowed to use the service worker in the code-server which using the self-signed certificate.

Hope to get your reply

**Comment by jsjoeio** [comment]
Thanks so much for the details! Do you know if it's possible to create a very minimal reproduction? 

I wonder if the issue is the SSL certificate 🤔

**Comment by hhc87** [comment]
@jsjoeio 
It may be difficult to send ssl certificates and other information (similar to docker-compose files) in the issue. I plan to try to provide a github repository address and put all the information in it, but it may take a while. I would also like to know if you can provide an email address where I can communicate with you by email so that we can communicate technical details more quickly.

**Comment by jsjoeio** [comment]
@hhc87 okay awesome! Unfortunately, I don't give out my email for those kinds of things, but I am subscribed to the repo and check notifications M-F so I will respond here!

**Comment by hhc87** [comment]
@jsjoeio 

Thank you for your patient reply, I created a small demo, the address is `https://github.com/hhc87/code-server-debug-demo`, mainly to deploy code-server and nginx through docker-compose, the specific information can be Get it in the u01 folder of the repo. Please also understand that for the sake of information security, I have not made this repository public, but have added you as a collaborator.At the same time, I don't know what problems will occur during the reproduction process. If you encounter an exception, please leave a message and contact me in time.

**Comment by fritterhoff** [comment]
Just as a note: From several different dev. projects I can confirm, that Chrome or prop. all Chromium Browsers are rather strict and reject the usage of self signed certificates for service workers. @jsjoeio I think there is no way to fix this in code-server since this is a known behavior and discussed several times in the community (e.g. https://stackoverflow.com/questions/38728176/can-you-use-a-service-worker-with-a-self-signed-certificate) ...

**Comment by fritterhoff** [comment]
> @fritterhoff oh no! I wonder what we should do then 🤔 Do we update the docs, remove the self-signed certificate generation inside code-server, or something else? I think @code-asher and I will need to discuss this next month.

Maybe that changed during some of the last releases but iirc chrome was rather picky. Maybe I find some time the next days to try it again 😉

**Comment by jerrywangjy** [comment]
hello, i also met with this problem, and my code-server version is 4.13.0.  It's ok with a firefox(latest version), but failed with chrome or edge. Do you have some plan to deal with the problem?

**Comment by jerrywangjy** [comment]
By the way, my client OS is windows~

**Comment by code-asher** [comment]
No plans at the moment, I will need to find time to reproduce but it be a while.

**Comment by lord-dubious** [comment]
its back again

**Comment by hanyixuanten** [comment]
same issue again in 2024

**Comment by phphoenix** [comment]
I was able to resolve the issue by switching from Chrome to Firefox. With Firefox, Jupyter Notebooks load fine and run. I also installed the .crt file from the server into my Windows machine, which may have helped with the switch to Firefox.

**Comment by zacdreyer-medbrief** [comment]
This still seems to be an issue. I have also had a look at multiple browsers and can confirm that it appears to be an issue with Chrome. On Firefox I do not get the problem. Thank you to @code-asher for pointing out that it worked on FireFox.

**Comment by mnowotnik** [comment]
Maybe related, fyi, code-server ran with self-signed cert properly shows images on Firefox, doesn't on Brave.

**Comment by code-asher** [comment]
Hmm yeah could be, if I recall correctly in Firefox if you accept an untrusted certificate then browser features like service workers will still work, but in Chrome accepting the certificate only lets you view the page, it still will not allow service workers (for that you have to set some "treat as secure" setting).

**Comment by James-Leong** [comment]
Chrome does not allow service workers, which has taken me a lot of time to troubleshoot...

**Comment by unclemusclez** [comment]
👀can confirm this still seems to be an issue. I stumbled across it with OpenSandbox. Granted, I am using self-signed certificates and no domain, just direct IP.

I've also tried it with nginx reverse proxy, and just added the cert to coder directly, along with generating multiple instances with OpenSandbox with docker containers.

perhaps i am implementing it wrong, but there doesnt seem to be much appropriate documentation on this, or i just haven't found it yet.
