### ISSUE TITLE
[Bug]: Image not showing up

### ISSUE THREAD

**Issue by gogobd** [coder/code-server#4800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: MacOS Monterey
- Remote OS: debian
- Remote Architecture: amd54
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

### Steps to Reproduce

1. run code-server --bind-addr 0.0.0.0:443 --cert -- /app
2. Connect to the address
3. Click an image

### Expected

Image should be shown in editor

### Actual

An SSL certificate error occurred when fetching the script.
log.ts:313   ERR [Service Worker] registration DOMException: Failed to register a ServiceWorker for scope ('https://--server--/') with script ('https://--server--/service-worker.js'): An SSL certificate error occurred when fetching the script.

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Please note i'm running it in docker but 443 is exposed (via 8080 in my case).

This is a re-opening of https://github.com/coder/code-server/issues/4658

**Comment by gogobd** [comment]
Additionally "Cannot reconnect. Please reload the window." pops up after some minutes... that's probably related.

**Comment by jsjoeio** [comment]
I was able to reproduce this locally on macOS + Brave with `code-server --bind-addr 0.0.0.0:443 --cert`

![image](https://user-images.githubusercontent.com/3806031/151459496-ee880bd3-d259-4e1d-b59a-061c04555b24.png)

```javascript
Error loading webview: Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://localhost/webview/6659afd9-08e4-4b14-9528-570c9d7107cc/') with script ('https://localhost/webview/6659afd9-08e4-4b14-9528-570c9d7107cc/service-worker.js?id=a8c6338a-43f4-450a-a373-44c7b0e0d34a&swVersion=2&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Flocalhost'): An SSL certificate error occurred when fetching the script..
```

@code-asher any ideas on where to troubleshoot the cause of this? I haven't spent much time generating SSL certificates locally before. I wonder what broke there.

**Comment by enric1994** [comment]
In the meantime, you can use version 3.9.1 if you really have to display images:

`docker pull codercom/code-server:3.9.1`

**Comment by gogobd** [comment]
I updated to version 4.0.2 and this issue seems to be fixed!

**Comment by enric1994** [comment]
Still not working for me. I have the following setup:

docker-compose.yml:
```
vscode:
    image: codercom/code-server:4.0.2
    ports:
      - "8080:8080"
    volumes:
      - ../:/desk/
      - ./:/home/coder/.config/code-server/
    restart: always
    user: "1000:1000"
```

config.yaml:

```
bind-addr: 127.0.0.1:8080
auth: password
password: 1234
cert: false
```

I access it using a tunnel (Ngrok)

**Comment by gogobd** [comment]
I realised that it did work when docker was running on the same machine, but not when code server was on another machine. Reopening.

**Comment by gogobd** [comment]
I tried the same Dockerfile on two machines, localhost and another. My browser (Brave Browser) one time shows an exclamation mark with a circle around it (localhost) and on the remote machine it shows an exclamation mark with a triangle around it. On localhost the image is shown, from the remote host it isn't.

Maybe this message in console is a hint:
```
Uncaught (in promise) Error: Service Workers are not enabled. Webviews will not work. Try disabling private/incognito mode.
    at :8180/webview/1e6c8813-ba31-4e1f-bb46-d48f13a2b8b2/main.js:115:83
    at new Promise (<anonymous>)
    at :8180/webview/1e6c8813-ba31-4e1f-bb46-d48f13a2b8b2/main.js:115:23
```

I don't see this on localhost.

**Comment by jsjoeio** [comment]
> accessing it via http.

Images are rendered in webviews. Webviews use Service Workers. Browsers require HTTPS to enable Service Workers. Therefore, this isn't a bug in code-server since it's not something we can change :( 

The only solution I can offer is to use HTTPS

**Comment by gogobd** [comment]
But why does it work on localhost?

**Comment by gogobd** [comment]
When I run code server with "--cert" to ask it to generate self-signed certificates i get

```
Error loading webview: Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://localhost:8080/webview/0abd743e-7e8b-4e72-a0c5-07c32e890f5e/') with script ('https://localhost:8080/webview/0abd743e-7e8b-4e72-a0c5-07c32e890f5e/service-worker.js?id=e0f9b720-4357-404a-87d5-060b4629d1d7&swVersion=2&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Flocalhost%3A8080'): An SSL certificate error occurred when fetching the script..
```

when I click on an image...

**Comment by jsjoeio** [comment]
> But why does it work on localhost? Maybe browsers don't block Service Workers over http on localhost?

I don't fully understand why/how it works, but yes, I think browsers allow localhost. See [this answer on S/O](https://stackoverflow.com/a/34161385/3015595)

> When I run code server with "--cert" to ask it to generate self-signed certificates i get

I believe this is a different error which should be fixed in the next version:[ ](https://github.com/coder/code-server/issues/4773)

**Comment by gogobd** [comment]
Thank you for mentioning this issue there! Let's hope this can be fixed "at the source".

**Comment by antofthy** [comment]
I am also seeing this with code-server v4.0.2   -- which is the latest release available at this time (18 Feb 2022)

I do hope a new release is provided soon, as in 2 week the new semester begins and I would like to upgrade the version the students are using.

**Comment by ky1emoon** [comment]
still not working with code-server v4.1.0 

1. installed code-server normally
2. `code-server --port 60000 --cert` 
3. still getting below error with self-signed cert
![image](https://user-images.githubusercontent.com/14849142/159110280-eada1954-dd5e-47e6-aeab-28a77f45d6c8.png)

**Comment by jsjoeio** [comment]
@ky1emoon can you try with 4.2.0?

Based on that error, it seems like you're not using HTTPS or your browser doesn't recognize the validity of your certificate perhaps. You could also share browser logs.

**Comment by jsjoeio** [comment]
Can someone verify if this is still an issue with 4.2.0?

**Comment by antofthy** [comment]
I have install v4.2.0 in testing.   Looks like the reconnect issue has been resolved as I am not seeing them any more.
I will now look at update the images student use from  v3.12.0  to  v4.2.0

**Comment by HaoLiuHust** [comment]
I am using v4.2.0, still has this problem

**Comment by gogobd** [comment]
I am also using v4.2.0 now, seeing """Error loading webview: Error: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://.../static/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://.../static/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-webview.net'): An SSL certificate error occurred when fetching the script.."""

**Comment by jsjoeio** [comment]
Hmm...okay we will have to dig into this again. Sorry y'all!

Thank you for the notes!

**Comment by gogobd** [comment]
That could well be related to https://github.com/coder/code-server/issues/4421 i suppose...

**Comment by gogobd** [comment]
Still broken in 4.3.0
<img width="467" alt="Screenshot 2022-04-19 at 19 30 59" src="https://user-images.githubusercontent.com/728976/164061877-378fc988-2b5d-47a1-9341-9628cdbf49b1.png">

**Comment by jsjoeio** [comment]
@gogobd thanks for confirming! Are you sure that your browser sees your SSL certificate as valid?

**Comment by gogobd** [comment]
@jsjoeio I always have to confirm that I want to accept the certificate:

<img width="619" alt="Screenshot 2022-04-19 at 20 56 56" src="https://user-images.githubusercontent.com/728976/164076145-8c647f50-8c6f-42ef-832b-276df5e26b09.png">

After confirming the browser marks it as not secure:

<img width="377" alt="Screenshot 2022-04-19 at 20 59 09" src="https://user-images.githubusercontent.com/728976/164076379-38c2ae1e-b5d1-4242-95bb-eae0fa5e23e0.png">

I run code-sever in docker using `--cert' :

CMD ~/.local/bin/code-server --cert --bind-addr 0.0.0.0:8080 /app

**Comment by jsjoeio** [comment]
Thanks for the details! That part sounds like it's working as expected 🤔 We'll have to dig into this.

**Comment by gogobd** [comment]
I was wondering if there's any news on this...

**Comment by jsjoeio** [comment]
Unfortunately not :( I've been pulled onto another project so my code-server work as slowed down this month. Hopefully soon though! PRs/help welcome though

**Comment by benz0li** [comment]
@gogobd Have a look at [mkcert](https://github.com/FiloSottile/mkcert) for making locally-trusted development certificates.

**Comment by gogobd** [comment]
This could all be the same problem, I'm using "--cert", see https://github.com/coder/code-server/issues/5338

**Comment by gogobd** [comment]
I updated to 4.9.0 and it seems to me that the certificates that are being generated on startup are not valid for brave, it shows 
<img width="368" alt="Screenshot 2022-12-10 at 12 52 04" src="https://user-images.githubusercontent.com/728976/206853897-fcb82391-fff3-4717-a6b9-1d13a439d50d.png">
after accepting the exception. Safari shows a lock sign indicating valid encryption, but it does show images. However Python Notebooks are displayed as text, but that's another issue. Is it not possible to automatically generate a certificate on startup that can be manually accepted in Chrome based browsers?

**Comment by jsjoeio** [comment]
I think something changed in Chromium that prevents it from accepting self-signed certificates or something 🤔 

cc @code-asher do you remember where we read that?

**Comment by gogobd** [comment]
I found a way to get Brave to work on MacOS.
I used `openssl s_client -connect localhost:8080` to retrieve the auto-generated (self-signed) certificate from the running code-server instance. I created a file with the extension `.crt` so I could import that key into `Keychain Access.app`. Then I used the search function in Keychain Access and double-clicked the new certificate to select "Always trust".
This enables all features other browsers don't seem to have an issue with - images are shown, Webviews seem to work ok, Jupyter Notebooks run.

This might also be an acceptable workaround for https://github.com/coder/code-server/issues/5338 .

**Comment by code-asher** [comment]
Yeah if I recall correctly it will unequivocally refuse insecure certificates for web workers (which are used by web views).  Other browsers like Firefox are OK using it for web workers as long as you accept the initial prompt.

**Comment by benz0li** [comment]
@gogobd Please close the issue when it is resolved.

**Comment by gogobd** [comment]
Note: `openssl s_client -connect localhost:8480 -showcerts </dev/null 2>/dev/null | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p'` shows the certificate ready to be used.
