### ISSUE TITLE
`Remote Extension host terminated unexpectedly 3 times within the last 5 minutes.`

### ISSUE THREAD

**Issue by JiaY-shi** [coder/code-server#7246]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: debian testing
- Remote Architecture:
- `code-server --version`: amd64

### Steps to Reproduce

1.
2.
3.

### Expected

The extension function should work normally

### Actual

Currently, when I open code-server, the extended functions cannot be used normally and it always prompts that it is closed. I mainly use git-related functions.

### Logs

```shell
[TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'issuerCertificate' closes the circle
	at JSON.stringify (<anonymous>)
	at tE (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:29:114967)
	at ei.serializeRequestArguments (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:29:122949)
	at Uy.U (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:29:119189)
	at s.<computed>.n.charCodeAt.s.<computed> (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:29:116531)
	at file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:117:679
	at file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:7:96
	at Array.forEach (<anonymous>)
	at SP.c (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:7:84)
	at SP.onUnexpecte
2025-03-04 16:32:16.268 [info] [127.0.0.1][6946608c][ExtensionHostConnection] <48594><stderr> dError (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:7:259)
	at ft (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:7:546)
	at process.<anonymous> (file:///usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:190:14445)
	at process.emit (node:events:518:28)
	at process._fatalException (node:internal/process/execution:188:25)]

Node.js v20.18.1

2025-03-04 16:32:16.276 [info] [127.0.0.1][6946608c][ExtensionHostConnection] <48594> Extension Host Process exited with code: 7, signal: null.
2025-03-04 16:32:16.391 [error] [127.0.0.1][6946608c][ExtensionHostConnection] Unknown reconnection token (seen before).
2025-03-04 16:32:16.544 [info] [127.0.0.1][b83f00f1][ExtensionHostConnection] New connection established.
2025-03-04 16:32:16.547 [info] [127.0.0.1][b83f00f1][ExtensionHostConnection] <48797> Launched Extension Host Process.
```
logs
```
[16:37:21] [127.0.0.1][6fdb3f2c][ExtensionHostConnection] Unknown reconnection token (seen before).
[16:37:28] [127.0.0.1][68ff3a5e][ExtensionHostConnection] Unknown reconnection token (seen before).
[16:37:35] [127.0.0.1][935e1dc6][ExtensionHostConnection] Unknown reconnection token (seen before).
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda_bg.wasm
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda_bg.wasm
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js
[16:39:39] [127.0.0.1][2e8541ad][ExtensionHostConnection] Unknown reconnection token (seen before).
[16:39:42] [127.0.0.1][2286d501][ExtensionHostConnection] Unknown reconnection token (seen before).
[16:39:46] [127.0.0.1][0cc2ce3f][ExtensionHostConnection] Unknown reconnection token (seen before).
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda_bg.wasm
```

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

**Comment by code-asher** [comment]
Does this happen without any extensions installed?  It would be good to test in Codespaces as well, it seems more likely to be an upstream VS Code issue than a code-server issue.

**Comment by JiaY-shi** [comment]
> Does this happen without any extensions installed? It would be good to test in Codespaces as well, it seems more likely to be an upstream VS Code issue than a code-server issue.

@code-asher When I uninstalled all plugins, the problem still exists.

**Comment by code-asher** [comment]
Interesting, it might be coming from a built-in extension in that case.  We upgraded VS Code yesterday to 1.98.0, once we get that out in a code-server release we should test to see if the problem remains (should be done today).

**Comment by JiaY-shi** [comment]
> Interesting, it might be coming from a built-in extension in that case. We upgraded VS Code yesterday to 1.98.0, once we get that out in a code-server release we should test to see if the problem remains (should be done today).

@code-asher In version [v4.98.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.98.0-rc.1), had the same problem

**Comment by code-asher** [comment]
Oh interesting that downgrading to 4.96.4 works.  The only major thing that happened between those releases was updating VS Code, so it does seem likely the problem is in VS Code itself, or in one of the built-in extensions.  🤔 

I see they fixed a similar issue (https://github.com/microsoft/vscode/issues/242036) but supposedly it was fixed in 1.98.0, so I would have expected the RC to work if it was the same issue.

**Comment by afshawnlotfi** [comment]
Still getting same issue even after downgrading to 4.96.4

**Comment by JiaY-shi** [comment]
@code-asher The same problem still occurs when using the latest version (4.98.2), and the CPU usage is found to be very high during on-site debugging.

nginx conf
```
server {
    listen 443 ssl;
    listen 444 ssl;
    listen 80;
    server_name coder.xxxx.cn;

    if ($scheme = http) {
        rewrite ^(.*)$ https://$host$1 permanent;
    }

    # ssl
    ssl_certificate ./ssl/netshi.cn/fullchain.cer;
    ssl_certificate_key ./ssl/netshi.cn/xxxx.cn.key;
    ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE';
    ssl_prefer_server_ciphers on;

    # To allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 0;
    # To disable buffering
    proxy_buffering off;

    location / {
      proxy_pass        http://127.0.0.1:8080;
      proxy_set_header  Host $http_host;
      proxy_set_header  X-Forwarded-Host $http_host;
      proxy_set_header  Upgrade $http_upgrade;
      proxy_set_header  Connection upgrade;
      proxy_set_header  Accept-Encoding gzip;
   }
}
```

code-server conf
```
bind-addr: 127.0.0.1:8080
auth: password
password: xxxxxxx
cert: false
```

**Comment by code-asher** [comment]
Interesting.  How exactly are you reproducing?  I am not seeing it after trying a few git operations (I tried staging, unstaging, reverting, and committing).

**Comment by JiaY-shi** [comment]
> Interesting. How exactly are you reproducing? I am not seeing any errors after trying a few git operations (I tried staging, unstaging, reverting, and committing).

@code-asher There are no other special operations or configurations, and the problem remains even if I install the latest version.

**Comment by JiaY-shi** [comment]
@code-asher Maybe I found the cause of the problem.
After I started network packet capture, I found that code-server would request the URL address `https://mobile.events.data.microsoft.com/OneCollector/1.0`, which was blocked by the ad filter on my gateway side, and would return incorrect certificate information, which led to a series of subsequent errors. Temporarily turning off the ad filter or whitelisting the domain name can solve the problem. I have not yet investigated why versions before 4.96.4 were also blocked and why there were no such problems.

**Comment by code-asher** [comment]
Nice find!  I wonder if disabling telemetry would also work.

**Comment by superpositionseeker** [comment]
updated code-server today (4.101.2) over (4.100.3) and now experiencing this issue. I have telemetry disabled.

**Comment by code-asher** [comment]
@superpositionseeker please feel free to open an issue with logs, etc.

**Comment by svefro** [comment]
similar issue here, please reopen issue

<img width="534" height="167" alt="Image" src="https://github.com/user-attachments/assets/a64ad800-4389-4097-8c68-a15c7c309aff" />

actual domain replaced with 'this.domain.com'

config.yaml
````
bind-addr: 127.0.0.1:8443
auth: password
password: notshownhere
cert: false
proxy-domain: this.domain.com
````

routed though cloudflare tunel on domain 'this.domain.com' 


[2025-07-30T19:53:08.149Z] info    - Proxying the following domain:
[2025-07-30T19:53:08.150Z] info      - {{port}}.this.domain.com
[2025-07-30T19:53:08.151Z] info  Using proxy URI in PORTS tab: //{{port}}.this.domain.com
[2025-07-30T19:53:08.152Z] info  Session server listening on /home/svefro/.local/share/code-server/code-server-ipc.sock
[21:53:09] 




[21:53:09] Extension host agent started.
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda_bg.wasm
File not found: /usr/lib/code-server/lib/vscode/node_modules/vsda/rust/web/vsda.js
[21:53:12] [127.0.0.1][8a1c6777][ManagementConnection] New connection established.

**Comment by code-asher** [comment]
@svefro are you able to reproduce without Cloudflare?  If so could you open a new issue with the logs from the browser console as well?

**Comment by svefro** [comment]
The issue was solved by adding more ram to the VM
